name: pvs_transport_env
channels:
  - conda-forge/label/fenics-dev
  - conda-forge
dependencies:
  - fenics-dolfin=2019.2.0.dev
  - openmpi<5 # ex3 segfaults with openmpi5
  - python=3.9    
  - numpy
  - numpy-indexed
  - ipython
  - matplotlib
  - pyvista
  - scikit-image
  - meshio
  - seaborn
  - nibabel
  - pip
  - tqdm
  - typer
  - pykdtree
  - bioconda::snakemake
  - libopenblas=*=*openmp*
  - gcc<13 # fTetWild install via pip requires gcc<13
  - pip:
    - pyacvd
    - cmocean
    - dufte
    - kimimaro
    - git+https://github.com/MiroK/ulfy.git@ufl_legacy
    - git+https://github.com/MiroK/fenics_ii.git@ufl_legacy
    - git+https://github.com/blocknics/cbc.block.git@mirok/ufl_legacy
    - git+https://github.com/MariusCausemann/wildmeshing-python.git
