name: pvs_transport_env
channels:
  - conda-forge
dependencies:
  - fenics-dolfin
  - python=3.9    
  - numpy
  - numpy-indexed
  - ipython
  - matplotlib
  - pyvista
  - scikit-image
  - meshio
  - seaborn
  - nibabel
  - pip
  - typer
  - pykdtree
  - bioconda::snakemake
  - pip:
    - pyacvd
    - cmocean
    - dufte
    - kimimaro
    - git+https://github.com/blocknics/cbc.block.git
    - git+https://github.com/MiroK/fenics_ii.git@point-trace
    - git+https://github.com/MariusCausemann/wildmeshing-python.git
