# Author: Marie E. Rognes (meg@simula.no)
# License: MIT
#
# Make sure to have dependencies installed/available:
# conda activate pvs_transport_env 
# 
#
# How to run: 
# python3 scripts/movie_story/make_story_video.py .
#

#import pyvista as pv
import typer
from pathlib import Path

from moviepy.editor import ImageSequenceClip, TextClip, CompositeVideoClip

def make_movie(framedir: str):
    # This overview function simply collects all frames (images),
    # connects them with text clips, and uses moviepy to 
    
    # Add all clips to this and composite video at the end
    clips = []
    
    # Main cover 
    title = "The brain's waterscape: in-silico molecular transport"
    txt_clip = TextClip(title, fontsize=70, color='white')
    txt_clip = txt_clip.set_position('center').set_duration(5)
    clips.add(txt_clip)
    
    # Collect the frames from different places
    # Load the frames generated by PyVista
    #clip_3d = ImageSequenceClip("frames/", fps=24)

    # Composite them
    video = CompositeVideoClip(clips)

    # Write final file
    filename = "insilico_transport.mp4"
    video.write_videofile(filename, fps=24)

    return filename

if __name__ == "__main__":

    typer.run(make_movie)

    
# def add_heading(pl, heading, frames):
#     # Show the heading for the given number of frames 
#     pl.add_text(heading, position=(200, 600), name="heading", font_size=24)
#     pl.show(auto_close=False)
#     for i in range(frames):
#         pl.write_frame()  

# def add_T1w_images(pl, datadir):

#     # Open and read the data first 
#     filename = Path(datadir, "data", "T1_synthseg.nii.gz")
    
#     print("Reading image from ", filename)
#     reader = pv.get_reader(filename) 
#     img = reader.read()
#     print(img)

    # # Set global plotting options for Pyvista
    # pv.set_plot_theme("dark")
    # pv.global_theme.font.family = "arial"
    # pv.global_theme.font.color = "white"

