from moviepy.editor import ImageSequenceClip, TextClip, CompositeVideoClip

# Load the frames generated by PyVista
clip_3d = ImageSequenceClip("frames/", fps=24)

# Create a text overlay (Title)
txt_clip = TextClip("The Digital Waterscape", fontsize=70, color='white')
txt_clip = txt_clip.set_position('center').set_duration(5)

# Composite them
video = CompositeVideoClip([clip_3d, txt_clip])

# Write final file
video.write_videofile("insilico_transport.mp4", fps=24)
